# Generated by Django 5.0.2 on 2024-03-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="address",
        ),
        migrations.RemoveField(
            model_name="job",
            name="description",
        ),
        migrations.RemoveField(
            model_name="job",
            name="email",
        ),
        migrations.RemoveField(
            model_name="job",
            name="title",
        ),
        migrations.AddField(
            model_name="job",
            name="Calle",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="Descripcion",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="Titulo",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="Email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
