# Generated by Django 5.0.2 on 2024-03-01 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_remove_job_address_remove_job_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="Calle",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="Descripcion",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="Titulo",
            new_name="title",
        ),
    ]
